### ISSUE TITLE
Update to Windows-2022?

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITKModuleTemplate#139]
Should we update this repository to use `Windows-2022` in CI for compatibility with latest wheels?

**Comment by tbirdso** [comment]
Yes, #140 will apply updates for v5.3rc04.post4 workflow changes prototyped in https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/pull/9/files
