### ISSUE TITLE
Upgrade to actions/checkout@v3

### ISSUE THREAD

**Issue by dyollb** [InsightSoftwareConsortium/ITKModuleTemplate#141]
## What is the issue?

actions/checkout@v2 is using deprecated version of node.js

<img width="966" alt="image" src="https://user-images.githubusercontent.com/12702862/204463046-6a29f3e4-c95a-4358-982b-6821d4a23417.png">

## How to fix

Upgrade to v3 (`actions/checkout@v3`)

E.g. here

https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/blob/007b02afbbb7572e5b38eb808cf8027980eb36bb/.github/workflows/build-test-package.yml#L148

And here: https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/blob/007b02afbbb7572e5b38eb808cf8027980eb36bb/%7B%7Bcookiecutter.project_name%7D%7D/.github/workflows/clang-format-linter.yml#L10

**Comment by thewtex** [comment]
@dyollb 👍

Could a PR please be created?

**Comment by thewtex** [comment]
Closed via #146
