### ISSUE TITLE
Update actions to use Node 20

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITKModuleTemplate#156]
This warning started appearing recently, e.g. [here](https://github.com/thewtex/ANTsWasm/actions/runs/7714122349?pr=10):

_Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4, lukka/get-cmake@v3.24.2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/._

**Comment by dzenanz** [comment]
@phcerdan @jhlegarreta was this done for some other repository recently? Can it be done here too?

**Comment by jhlegarreta** [comment]
> @phcerdan @jhlegarreta was this done for some other repository recently?

@dzenanz It has been done multiple times over the last few months, first for Node.js 16 and more recently for Node.js 20, e.g.:
https://github.com/InsightSoftwareConsortium/ITK/pulls?q=is%3Apr+is%3Aclosed+author%3Ajhlegarreta+node
https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/pulls?q=is%3Apr+is%3Aclosed+author%3Ajhlegarreta+node
https://github.com/InsightSoftwareConsortium/ITKSoftwareGuide/pulls?q=is%3Apr+is%3Aclosed+author%3Ajhlegarreta+node
etc.

> Can it be done here too?

Wish they were done in a separate commit, but Matt's PR is updating the action versions:
https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/pull/158/files
