### ISSUE TITLE
ITK Build failure in External Module

### ISSUE THREAD

**Issue by dyollb** [InsightSoftwareConsortium/ITKModuleTemplate#167]
I am adding a small feature to my external module and got a build error for ITK. Should I update the [github action](https://github.com/dyollb/ITKLabelPointSet/blob/main/.github/workflows/build-test-package.yml)?

https://github.com/dyollb/ITKLabelPointSet/actions/runs/11892961356/job/33136911530

<img width="962" alt="image" src="https://github.com/user-attachments/assets/6178bea2-c06d-40e5-abda-1f2b82c16f92">

**Comment by dzenanz** [comment]
https://github.com/InsightSoftwareConsortium/ITK/issues/4820 was fixed yesterday in the main repository.

**Comment by dyollb** [comment]
hmm. thanks @dzenanz. I would have assumed the action would take the tagged version 5.4.0, in order to make sure wheels built later are still based on a specific version and will be compatible...

- was the bug already in ITK==5.4.0, and if yes, why did my CI not fail previously?
- can I release the wheels even if the cxx windows build fails (all python stages succeed) by pushing a tag?

**Comment by dzenanz** [comment]
Maybe the MSVC version was updated in CI's Windows machine image? If the wheels build without errors, they should work, even if build-and-test fails due to compile error.

**Comment by dzenanz** [comment]
Yes, third party libraries are quite a fixed version, which is infrequently updated. `libTIFF` was not update in a decade, it seems. And yesterday's "refresh" was preparation for an update, not an update in itself.

**Comment by dyollb** [comment]
Seems the mac os version is deprecated. All non-arm mac os jobs were cancelled: 
https://github.com/dyollb/ITKLabelPointSet/actions/runs/11895490090

**Comment by dzenanz** [comment]
Here is how to update: https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/pull/75

I think I added it as a PR here too, but I can't find the PR now.

**Comment by dzenanz** [comment]
Ahh, that PR is here: https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/pull/95

**Comment by dyollb** [comment]
thanks, that is great. 

Can I use the fixed version by changing the tag from
```yml
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@v5.4.0
```
to
```yml
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@some-hash
```

**Comment by dzenanz** [comment]
Yes. We should probably also update 5.4.0 branch. @thewtex, @jhlegarreta, and @n-dekker, what do you think?

**Comment by thewtex** [comment]
Patch to address the libtiff symbol in remote module CI builds: https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/pull/97
