### ISSUE TITLE
Update/remove ref to ITKv4

### ISSUE THREAD

**Issue by jhlegarreta** [InsightSoftwareConsortium/ITKModuleTemplate#26]
The sentence
```
This is a module for the Insight Toolkit (ITK) for segmentation and registration.
It is designed to work with the ITKv4 modular system.
```
in the `README.rst` file will need to be updated: either changed for `ITKv5` or just `ITK`.

This fork has diverged from upstream so I ignore which one we should be using.

The ITK Wiki [mentions](https://itk.org/Wiki/ITK/Release_4/Modularization/Add_an_external_module_(external_module)) Brad's.

I mentioned the ISC fork in [PR #66](https://github.com/InsightSoftwareConsortium/ITKSoftwareGuide/pull/66/files) for the ITK SW Guide.

I think this applies to some remote modules as well.

@blowekamp @thewtex @fbudin69500 May be TBD in a t-con at some point?

**Comment by thewtex** [comment]
I think this is the canonical repository now.

Regarding the ITK modular system, we can just use `ITK` as opposed to `ITKv4`.
