### ISSUE TITLE
Add `examples` folder content to the module template

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKModuleTemplate#34]
See:

  https://github.com/KitwareMedical/ITKMorphologicalContourInterpolation/tree/master/examples

for what the content can be like.

**Comment by jhlegarreta** [comment]
Thanks @thewtex I'll add this over the next few days !

**Comment by dzenanz** [comment]
A blocker for adding examples here is https://github.com/InsightSoftwareConsortium/ITK/issues/359. Once that is resolved, PR #46 can be revived.
